// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestBlazorAPP.Database;

#nullable disable

namespace TestBlazorAPP.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ToDo")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestBlazorAPP.Models.Aufgabe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BildId")
                        .HasColumnType("int");

                    b.Property<bool>("Geloescht")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioritaet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BildId");

                    b.ToTable("Aufgabe", "ToDo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Geloescht = false,
                            Name = "Testaufgabe",
                            Prioritaet = 1
                        });
                });

            modelBuilder.Entity("TestBlazorAPP.Models.Bild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bild", "ToDo");
                });

            modelBuilder.Entity("TestBlazorAPP.Models.Aufgabe", b =>
                {
                    b.HasOne("TestBlazorAPP.Models.Bild", "Bild")
                        .WithMany()
                        .HasForeignKey("BildId");

                    b.Navigation("Bild");
                });
#pragma warning restore 612, 618
        }
    }
}
